projects:
  - name: "Go FaaS Template"
    root: "base"
    formGroups:
      - displayName: "Service Definition"
        imageGroup: false
      - displayName: "Runtime Selection"
        imageGroup: true
    language:
      name: "Go"
      version: "1.12"
    runtime:
      names:
        - "knative"
        - "kubernetes"
        - "lambda"
    options:
      - name: "projectName"
        required: true
      - name: "gitHost"
        required: true
      - name: "exe_name"
        default: "mylambda"
      - name: "docker_base"
        required: true
        default: "alpine:3.8"